language: elixir
elixir:
  - 1.0.0
  - 1.0.5
otp_release:
  - 17.1
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis
